#!/usr/bin/env lua
--[[
Copyright 2018 Marcos Gutierrez <gmarcos87@gmail.com>
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-3.0
]]--

require "ubus"
local json = require 'luci.json'

local function printJson (obj)
    print(json.encode(obj))
end

local conn = ubus.connect()
if not conn then
    error("Failed to connect to ubus")
end

local function shell(command)
    -- TODO(nicoechaniz): sanitize or evaluate if this is a security risk
    local handle = io.popen(command)
    local result = handle:read("*a")
    handle:close()
    return result
end

local function add_voucher(msg)
    local result = {}
    local key = msg.key
    local secret = msg.secret
    local epoc = msg.epoc
    local upload = msg.upload
    local download = msg.download
    local amountofmacsallowed = msg.amountofmacsallowed
    result.key = key
    result.secret = secret
    result.epoc = epoc
    result.upload = upload
    result.download = download
    result.amountofmacsallowed = amountofmacsallowed
    shell('voucher add_voucher '..key..' '..secret..' '..epoc..' '..download..' '..upload..' '..amountofmacsallowed)
    printJson(result)
end

local function auth_voucher(msg)
    local result = {}
    local mac = msg.mac
    local voucher = msg.voucher
    result.mac = mac
    result.voucher = voucher
    shell('voucher auth_voucher '..mac..' '..voucher)
    printJson(result)
end

local function print_valid_macs(msg)
    local result = {}
    result.macs = {}
    local output = shell('voucher print_valid_macs')
    for line in output:gmatch("[^\n]+") do
        -- local words = {}
        -- for w in line:gmatch("%S+") do if w ~= "" then table.insert(words, w) end end
        -- local mac = words[2]
        table.insert(result.macs, line)
    end
    printJson(result);
end

local function status(msg)
    local result = {}

    printJson(result);
end

local methods = {
  add_voucher = {
    key = 'value',
    secret = 'value',
    epoc = 0,
    upload = 0,
    download = 0,
    amountofmacsallowed = 0
  },
  auth_voucher = { mac = 'value', voucher = 'value' },
  print_valid_macs = { no_params = 0 },
  status = { no_params = 0 }
}

if arg[1] == 'list' then
    printJson(methods)
end

if arg[1] == 'call' then
  local msg = io.read()
  msg = json.decode(msg)
  if       arg[2] == 'add_voucher'	        then add_voucher(msg)
  elseif   arg[2] == 'auth_voucher'	        then auth_voucher(msg)
  elseif   arg[2] == 'print_valid_macs'	    then print_valid_macs(msg)
  elseif   arg[2] == 'status'	            then status(msg)
  else                                      printJson({ error = "Method not found" })
  end
end
