#!/usr/bin/lua

print("Status: 302 \n\n")
print("Content-type: text/html \n\n")
local url = os.execute("uci get pirania.base_config.portal_url")
print(string.format([[
<!doctype html>
<html>
  <head>
    <title>Redirect</title>
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="Refresh" content="0; url=%s">
     <!-- If the meta tag doesn't work, try JavaScript to redirect. -->
     <script type="text/javascript">
      window.location.href = %q
    </script>
  </head>
   <body>
    <!-- If JavaScript doesn't work, give a link to click on to redirect. -->
     <p><a href=%q>ENTER</a></p>
  </body>
</html>
]], url, url , url))