#!/usr/bin/lua

local uci = require('uci')
local json = require('luci.json')
local uci_cursor = uci.cursor()

function handle_request (env)
  local origin_url = env.HTTP_HOST
  local portal_url = uci_cursor:get("pirania", "base_config", "portal_url")
  local url = portal_url..'?prev='..origin_url
  local send = uhttpd.send
  send("Status: 302 \r\n")
  send("Content-type: text/html \n\n")
  send(string.format([[
    <!doctype html>
    <html>
      <head>
        <title>Redirect</title>
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="Refresh" content="0; url=%s">
        <!-- If the meta tag doesn't work, try JavaScript to redirect. -->
        <script type="text/javascript">
          window.location.href = %q
        </script>
      </head>
      <body>
        <!-- If JavaScript doesn't work, give a link to click on to redirect. -->
        <p><a href=%q>ENTER</a></p>
      </body>
    </html>
  ]], url, url , url))
end
