#!/bin/sh
echo "Status: 200 OK"
echo "Transfer-Encoding: chunked"
echo "Content-Type: text/html"
echo "Cache-Control: no-cache"
echo "Expires: 0"
echo "Access-Control-Allow-Origin: *"
echo

gatewayname="$HTTP_HOST"
client_ip="$REMOTE_ADDR"

client_mac="$(/usr/bin/ip neigh show to $client_ip | sed -n '/.* \(..:..:..:..:..:..\) .*/s//\1/p' | sort -u)"

. /usr/bin/vale.sh check "$client_mac"

if [ "$vale_expire_epoch" -gt "$now_epoch" ] ; then
  message="Your voucher is still valid, until $(date +'<b>%F</b> at %T' -d @$vale_expire_epoch)"
  message="$message<br>Just click OK (no need to type anything)."
else
  message="There's no voucher linked to this device."
  if [ -n "$free_first_use_epoch" ] ; then
    message="$message<br>You already used the <em>$free_keyword</em> voucher this month"
    message="$message<br>$(date +'on date %F at %T' -d @$free_first_use_epoch)."
    if [ "$free_remaining_secs" -gt 0 ] ; then
      message="$message<br>You can continue browsing for <b>$(($free_remaining_secs/3600)) hours</b>"
      message="$message<br>(until $(date +'%F at %T' -d @$free_expire_epoch))."
      message="$message<br>Just click OK (no need to type anything)."
    else
      message="$message<br>It's vital to have at least a <b>minimum</b> engagement"
      message="$message<br>and <b>social ties</b> with the community, therefore"
      message="$message<br><b>your web browsing is blocked until you obtain a voucher</b>."
    fi
  else
    message="$message<br>If you're in a hurry, get 24hs of web browsing with the special voucher <b>$free_keyword</b>,"
    message="$message<br>but note you can only enjoy this privilege once a month."
  fi
fi

cat <<EOF
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>$title</title>
<meta HTTP-EQUIV='Pragma' CONTENT='no-cache'>
</head>
<body>
<div>
  <div style="text-align: center">$message</div>
</div>
</body>
</html>
EOF

exit 1
