#!/bin/sh
echo "Status: 200 OK"
echo "Transfer-Encoding: chunked"
echo "Content-Type: text/html"
echo "Cache-Control: no-cache"
echo "Expires: 0"
echo "Access-Control-Allow-Origin: *"
echo

gatewayname="$HTTP_HOST"
client_ip="$REMOTE_ADDR"

client_mac="$(/usr/bin/ip neigh show to $client_ip | sed -n '/.* \(..:..:..:..:..:..\) .*/s//\1/p' | sort -u)"

voucher_expiretime="$(voucher status "${client_mac:-unknown_mac}" | cut -f 1)"

tolower() { echo "$@" | tr ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz ; }
voucher="$(tolower "${QUERY_STRING##voucher=}" | tr -c -d abcdefghijklmnopqrstuvwxyz1234567890)"

if [ -n "$voucher" ] ; then
  voucher_expiretime="$(voucher auth_voucher "${client_mac:-unknown_mac}" "${voucher}" | cut -f 1)"
fi

if [ "$voucher_expiretime" -gt "0" ] ; then
  voucher_expire_epoch=$(($voucher_expiretime+$(date +%s)))
  message="Your voucher is valid, until $(date +'<b>%F</b> at %T' -d @$voucher_expire_epoch)"
else
  message="There's no voucher linked to this device."
  form='
    <form method="GET" action="">
      <input type="text" name="voucher" id="voucher" autocomplete="off" value="" size="12"/>
      <input type="submit" value="OK" /><br/>
    </form>
    '
fi

cat <<EOF
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>$title</title>
<meta HTTP-EQUIV='Pragma' CONTENT='no-cache'>
</head>
<body>
<div>
  <div style="text-align: center">$message</div>
  <div style="text-align: center">$form</div>
</div>
</body>
</html>
EOF

exit 1
