#!/usr/bin/lua

local http = require('luci.http')
local logic = require('voucher.logic')
local dba = require('voucher.db')
local query_string = os.getenv("QUERY_STRING")

print("Content-type: text/html \n\n")

local res = logic.getIpv4AndMac()
params = http.urldecode_params(query_string)
local voucher = params['voucher']
local mac = res.mac
local prevUrl = params['prev']
local valid = logic.check_mac_validity(res.mac)

local url = 'http://thisnode.info/portal/auth_fail.html'
local output
local success = false

if (voucher and mac) then
  local authCommand = "voucher auth_voucher " .. mac .. " ".. voucher
  ac = io.popen(authCommand, 'r')
  output = ac:read('*l')
  ac:close()
  local num = string.sub(output, 1, 1, 1)
  print(num)
  print(tonumber(num))
  print(tonumber(num) > 0)
  success = tonumber(num) > 0
  print(success)
  if (success == true or valid > 0) then
    if (prevUrl ~= nil) then
      url = 'http://'..prevUrl
    else
      url = 'http://thisnode.info/portal/authenticated.html'
    end
   end
end

print(string.format([[
<!doctype html>
<html>
  <head>
    <title>Redirect</title>
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="Refresh" content="0; url=%s">
    <!-- If the meta tag doesn't work, try JavaScript to redirect. -->
    <script type="text/javascript">
      window.location.href = %q
    </script>
  </head>
  <body>
    <!-- If JavaScript doesn't work, give a link to click on to redirect. -->
    <p><a href=%q>ENTER</a></p>
  </body>
</html>
]], url, url , url))

