#!/usr/bin/lua

local http = require('luci.http')

local query_string = os.getenv("QUERY_STRING")

print('Content-Type: text/plain\r\n\r\n')
params = http.urldecode_params(query_string)

print(params['mac'])
-- if params == mac