#!/bin/sh /etc/rc.common

START=99
NAME=pirania
PROG=/usr/bin/captive-portal

start() {
    if  [ $(uci get pirania.base_config.enabled) == 1 ]; then
        logger -t pirania "Running portal captive"
        $PROG
    else
        logger -t pirania "Portal captive is disabled"
    fi
}

stop () {
    logger -t pirania "Portal captive - to be implemented"
}
